# Generated by Django 5.0.1 on 2025-04-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0008_alter_studentsubmission_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsubmission',
            unique_together=set(),
        ),
    ]
